
public class TesteErro {
	
	public static void main(String[] args) {
		System.out.println("Início do main");
		metodo1();
		System.out.println("Fim do main");
	}
	
	static void metodo1() {
		System.out.println("Início do método 1");
		metodo2();
		System.out.println("Fim do método 2");
	}
	
	static void metodo2() {
		
		try {
			System.out.println("Início do método 2");
			int[] array = new int[10];
			
			for(int i = 0; i <= 15; i++)
			{
				array[i] = i;
				System.out.println("Valor i: " + i);
			}
			System.out.println("Fim do método 2");
			
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("Erro: " + e.getCause() + " - " + e.getMessage());
		}
		
	}
}
